### ISSUE TITLE
Error No module named 'pip.req'

### ISSUE THREAD

**Issue by aliciawyy** [flupke/freeze-requirements#11]
Hello,
I got the following error with the latest version of the package, it doesn't run at all with all the commands you suggested.

my env is

Python 3.5.2
pip 10.0.1

```
(py35-rrm) ~$ freeze-requirements freeze --separate-requirements requirements.txt requirements2.txt
Traceback (most recent call last):
  File "/home/alice/.virtualenvs/py35-rrm/bin/freeze-requirements", line 7, in <module>
    from freezerequirements.cli import main
  File "/home/alice/.virtualenvs/py35-rrm/lib/python3.5/site-packages/freezerequirements/cli.py", line 12, in <module>
    from pip.req import InstallRequirement
ImportError: No module named 'pip.req'
```

**Comment by Syntactical01** [comment]
Same with with Python3.8 Pip 20.3.1

**Comment by flupke** [comment]
Hello, I don't maintain this package anymore sorry, I'll gladly accept PRs though :)

**Comment by bertranddemiddelaer** [comment]
@flupke here is a PR with the fix... https://github.com/flupke/freeze-requirements/pull/12

**Comment by bertranddemiddelaer** [comment]
Now that the PR is merged, I think this issue should be closed

**Comment by bertranddemiddelaer** [comment]
@flupke will you release a new official version with the fix ?

**Comment by flupke** [comment]
@bertranddemiddelaer I could transfer you the ownership of this repo and the pypi package, wdyt?

**Comment by KIC** [comment]
I am running into the same issue using github actions. can you please release this fix. :pray:

**Comment by flupke** [comment]
Hello @KIC, as said above, I don't have time or will to maintain this package anymore, mainly because there are better alternatives these days to achieve what this package was created for, like poetry.
